# Generated by Django 3.0.3 on 2020-07-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userlogin',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
